[package]
name = "demo-fatfs"
edition = "2021"

[dependencies]
unico.workspace = true
fatfs = "0.3"
tokio.workspace = true
chrono.workspace = true
rand = "0.8"
rand_pcg = "0.3"
futures = "0.3"
sha2 = "0.10"
