[package]
edition = "2021"
name = "unico-context"
version = "0.1.0"

[features]
boost = ["dep:cc"]
default = ["boost"]

[dependencies]
cfg-if = "1.0"

[build-dependencies]
cc = {version = "1.0", optional = true}
